"""add_sexo_atleta

Revision ID: b2ac10fcde8c
Revises: 53a35967eec1
Create Date: 2024-07-10 15:30:09.062025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ac10fcde8c'
down_revision: Union[str, None] = '53a35967eec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('sexo', sa.String(length=1), nullable=False))
    op.drop_constraint('atletas_nome_key', 'atletas', type_='unique')
    op.create_unique_constraint(None, 'atletas', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'atletas', type_='unique')
    op.create_unique_constraint('atletas_nome_key', 'atletas', ['nome'])
    op.drop_column('atletas', 'sexo')
    # ### end Alembic commands ###
